#%RAML 1.0

title: mod-custom-fields
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-custom-fields

documentation:
  - title: mod-custom-fields
    content: This documents the API calls that can be made to manage custom fields

types:
  customFieldCollection: !include customFieldCollection.json
  customField: !include customField.json
  customFieldStatisticCollection: !include customFieldStatisticCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  collection-readonly: !include raml-util/rtypes/get-only.raml


/custom-fields:
  displayName: Custom Fields
  type:
    collection:
      schemaCollection: customFieldCollection
      schemaItem: customField
      exampleCollection: !include examples/customFieldCollection.sample
      exampleItem: !include examples/customField.sample
  post:
    is: [ validate ]
  get:
    is: [
      searchable: {description: "Query should contain custom field attributes", example: "name=department"},
      pageable,
      validate
    ]
  /{id}:
    displayName: Custom Fields
    description: Get, Delete or Update a custom field
    type:
      collection-item:
        schema: customField
        exampleItem: !include examples/customField.sample
    /stats:
      displayName: Custom field usage statistic
      description: Returns usage statistic of custom field with the given id
      type:
        collection-readonly:
          schema: customFieldStatisticCollection
          exampleCollection: !include examples/customFieldStatisticCollection.sample
