#%RAML 1.0

title: mod-custom-fields
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-custom-fields

documentation:
  - title: mod-custom-fields
    content: This documents the API calls that can be made to manage custom fields

types:
  customFieldsCollection: !include customFieldsCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

/custom-fields:
  displayName: Custom Fields
  get:
    description: Retrieve a collection of custom fields based on the search query.
    is: [
      searchable: {description: "with valid searchable fields: for example genus=felis", example: "genus=felis"},
      pageable]
    responses:
      200:
        description: OK
        body:
          application/json:
            description: |
              An array of custom fields comprising the results of the query.
            type: customFieldsCollection
      400:
        description: Bad Request
        body:
          application/json:
            type: errors
